---
name: Pull request build

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test the action
    permissions:
      pull-requests: read
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create initial testing repository
        run: |
          mkdir ${{ github.workspace}}/tmprepo
          cd ${{ github.workspace }}/tmprepo
          git init
          echo "blabla" > file
          git add file
          git commit -m "build: initial commit"
          git tag -m "1.2.3" 1.2.3

      - name: Add commit of type fix
        working-directory: tmprepo
        run: |
          echo "blabla" > fix_file
          git add fix_file
          git commit -m "fix: fixed something"

      - name: Run local action for patch bump
        id: patch_bumper
        uses: ./
        with:
          folder: tmprepo

      - name: Verify patch bump
        if: >
          steps.patch_bumper.outputs.new_version != '1.2.4' ||
          steps.patch_bumper.outputs.next_dev_iteration != '1.2.5.dev' ||
          steps.patch_bumper.outputs.major_part != '1' ||
          steps.patch_bumper.outputs.minor_part != '2' ||
          steps.patch_bumper.outputs.patch_part != '4' ||
          steps.patch_bumper.outputs.patch_next_dev != '5.dev'
        uses: actions/github-script@v7
        with:
          script: core.setFailed('patch bump not working correctly')

      - name: Add commit of type feat
        working-directory: tmprepo
        run: |
          echo "blabla" > feat_file
          git add feat_file
          git commit -m "feat: added a new feature"

      - name: Run local action for minor bump
        id: minor_bumper
        uses: ./
        with:
          folder: tmprepo

      - name: Verify minor bump
        if: >
          steps.minor_bumper.outputs.new_version != '1.3.0' ||
          steps.minor_bumper.outputs.next_dev_iteration != '1.3.1.dev' ||
          steps.minor_bumper.outputs.major_part != '1' ||
          steps.minor_bumper.outputs.minor_part != '3' ||
          steps.minor_bumper.outputs.patch_part != '0' ||
          steps.minor_bumper.outputs.patch_next_dev != '1.dev'
        uses: actions/github-script@v7
        with:
          script: core.setFailed('minor bump not working correctly')

      - name: Add breaking commit
        working-directory: tmprepo
        run: |
          echo "blabla" > breaking_file
          git add breaking_file
          git commit -m "refactor: refactor some stuff

          BREAKING CHANGE: broke some stuff"

      - name: Run local action for major bump
        id: major_bumper
        uses: ./
        with:
          folder: tmprepo

      - name: Verify major bump
        if: >
          steps.major_bumper.outputs.new_version != '2.0.0' ||
          steps.major_bumper.outputs.next_dev_iteration != '2.0.1.dev' ||
          steps.major_bumper.outputs.major_part != '2' ||
          steps.major_bumper.outputs.minor_part != '0' ||
          steps.major_bumper.outputs.patch_part != '0' ||
          steps.major_bumper.outputs.patch_next_dev != '1.dev'
        uses: actions/github-script@v7
        with:
          script: core.setFailed('major bump not working correctly')

      - name: Run local action overriding the bump with a patch bump
        id: bumper_override
        uses: ./
        with:
          folder: tmprepo
          bumpoverride: patch

      - name: Verify overriding with patch bump
        if: >
          steps.patch_bumper.outputs.new_version != '1.2.4' ||
          steps.patch_bumper.outputs.next_dev_iteration != '1.2.5.dev' ||
          steps.patch_bumper.outputs.major_part != '1' ||
          steps.patch_bumper.outputs.minor_part != '2' ||
          steps.patch_bumper.outputs.patch_part != '4' ||
          steps.patch_bumper.outputs.patch_next_dev != '5.dev'
        uses: actions/github-script@v7
        with:
          script: core.setFailed('overriding the bump as a patch bump not working correctly')

      - name: Cleanup
        if: always()
        run: rm -rf ${{ github.workspace }}/tmprepo
