---
name: Pre-Release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  pre-release:
    runs-on: ubuntu-latest
    environment: staging
    name: Test the action
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.3.4

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create initial testing repository
        run: |
          mkdir ${{ github.workspace }}/tmprep
          cd ${{ github.workspace }}/tmprep
          git init
          echo "blabla" > file
          git add file.txt
          git commit -m "build: initial commit"

      - name: Run local action
        id: bumper
        uses: ${{ github.workspace }}
        with:
          label: .tst
          changelog: true

      - name: Verify patch bump
        if: |
          ${{ steps.bumper.outputs.new_version != '1.0.0' ||
              steps.bumper.outputs.next_dev_iteration != '1.0.1.tst' }}
        uses: actions/github-script@v4.1.0
        with:
          script: core.setFailed('bump not working correctly')

      - name: Verify changelog file exists
        if: hashFiles('CHANGELOG.md') != ''
        uses: actions/github-script@v4.1.0
        with:
          script: core.setFailed('changelog file not created')

      - name: Cleanup
        if: always()
        working-directory: ${{ github.workspace }}
        run: rm -rf ${{ github.workspace }}/tmprep
